### ISSUE TITLE
Example of server generated error after submitting?

### ISSUE THREAD

**Issue by tmepple** [alexfedoseev/re-formality#13]
Thanks for this great library!

I was looking at the `LoginForm.re` example for how to handle a server generated error message which is returned after submitting... such as "invalid login username or password".  I see we should call `notify.onFailure` but I'm not sure how to inject the server error string so it's returned with `form.results` on a specific field and can be rendered similarly.  

I guess I could process, store, and render the server error in state outside of re-formality but not sure if that's the right way to do it.

**Comment by alexfedoseev** [comment]
@tmepple Sorry, no way for now. But I'm working on it and I will pick up the pace 👍

Check out for more details: https://github.com/alexfedoseev/re-formality/issues/11#issuecomment-373610276

**Comment by tmepple** [comment]
Ah, wow that looks really cool.  Ok, I will store/render any server errors using local state at this point and look forward to the new release.  Thanks for working on it!
