### ISSUE TITLE
Global Form Validator

### ISSUE THREAD

**Issue by lukashambsch** [alexfedoseev/re-formality#45]
Is there a way to create a global form validator?

My use case is with a form that just requires any one of the fields to be completed for it to be valid. I can put the validation on a single field, but then the error message makes it look like that field is required.

My thought was making `field` in the validator optional. So you could do something like this:
```
let validator = {
      field: None,
      strategy: Strategy.OnFirstSuccessOrFirstBlur,
      dependents: Some([One, Two, Three, Four, Five]),
      validate: ({one, two, three, four, five}) =>
        switch (one, two, three, four, five) {
        | ("", "", "", "", "") =>
          Error("You must complete one of the fields.")
        | _ => Ok(Valid)
        },
    };
```

If there isn't a way now, do you have any suggestions on the best way to do it?

Thanks!

**Comment by alexfedoseev** [comment]
@lukashambsch Your validator looks good to me and I think you can solve UX issue by not displaying errors next to specific fields but somewhere where your users would consider an error as global to the form. Then, to figure out when to show an error you can just check results for each field and if any is in error state -> show global error. Does it work for you?

**Comment by lukashambsch** [comment]
The validator I showed above doesn't work for me because `field` is defined as `None`. It seems like field is expecting a value instead of an option.

**Comment by alexfedoseev** [comment]
Validator receives a state of a form, i.e. what you defined as a `state` type.

**Comment by lukashambsch** [comment]
Got it. So for the field it takes in what I define as the field type. That makes sense. Thanks!
